# Site settings
title: Elm (language) FAQ
description: > # this means to ignore newlines until "baseurl:"
  Unofficial FAQ for the Elm language.
baseurl: "/elm-faq" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  elm-community

# Build settings
markdown: kramdown

# The following are supposed to be defaults per
# https://help.github.com/articles/using-jekyll-with-pages/ but as of 2016-02-02
# I have to set them explicitly for correct output.
kramdown:
  input: GFM
  hard_wrap: false
  
